server:
  port: 9001
spring:
  application:
    name: activemq-producer
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin

#指定发送模式 false P2P ， true Pub/Sub
  jms:
    pub-sub-domain: false
